repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
        # See https://pre-commit.com/hooks.html for more hooks
        - id: check-ast
        - id: check-case-conflict
        - id: check-merge-conflict
        - id: debug-statements
        - id: end-of-file-fixer
        - id: name-tests-test
          args: [ "--django" ]
        - id: trailing-whitespace

    - repo: https://github.com/rtts/djhtml
      rev: 'v1.5.0'
      hooks:
        - id: djhtml

    - repo: https://github.com/ambv/black
      rev: 22.1.0
      hooks:
      - id: black

    - repo: local
      hooks:
        - id: django-test
          name: django-test
          entry: python manage.py test -v 1
          always_run: true
          pass_filenames: false
          language: system
