# Generated by Django 4.0.2 on 2022-02-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=30)),
                ("about", models.TextField(max_length=150)),
                ("image", models.ImageField(upload_to="static_cdn/admin/img")),
                ("firstname", models.CharField(max_length=30)),
                ("lastname", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=50)),
                (
                    "country",
                    models.IntegerField(
                        choices=[
                            ("USA", "United states"),
                            ("CA", "Canada"),
                            ("FR", "France"),
                        ]
                    ),
                ),
                ("address", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=60)),
                (
                    "state",
                    models.CharField(max_length=30, verbose_name="State/Province"),
                ),
                (
                    "zipcode",
                    models.CharField(max_length=8, verbose_name="Zip/Postal code"),
                ),
                (
                    "by_email",
                    models.IntegerField(
                        choices=[
                            ("COM", "Comments"),
                            ("Cand", "Candidates"),
                            ("OFF", "Offers"),
                        ]
                    ),
                ),
                (
                    "notifications",
                    models.BooleanField(
                        choices=[
                            ("EVE", "Everything"),
                            ("Cand", "Same as email"),
                            ("NOPUSH", "No push notifications"),
                        ]
                    ),
                ),
            ],
        ),
    ]
