# Generated by Django 4.0.2 on 2022-03-05 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=30)),
                ("about", models.TextField(max_length=150)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="media",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "png", "jpeg"]
                            )
                        ],
                    ),
                ),
                ("firstname", models.CharField(max_length=30)),
                ("lastname", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=50)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("USA", "United states"),
                            ("CA", "Canada"),
                            ("FR", "France"),
                        ],
                        max_length=10,
                    ),
                ),
                ("address", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=60)),
                (
                    "state",
                    models.CharField(max_length=30, verbose_name="State/Province"),
                ),
                (
                    "zipcode",
                    models.PositiveIntegerField(verbose_name="Zip/Postal code"),
                ),
                (
                    "by_email",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0", "Comments"),
                            ("1", "Candidates"),
                            ("2", "Offers"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "notifications",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0", "Everything"),
                            ("1", "Same as email"),
                            ("2", "No push notifications"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
