# Generated by Django 4.0.2 on 2022-02-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="by_email",
        ),
        migrations.AddField(
            model_name="customuser",
            name="by_email_candidates",
            field=models.BooleanField(default=False, verbose_name="Candidates"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="by_email_comments",
            field=models.BooleanField(default=False, verbose_name="Comments"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="by_email_offers",
            field=models.BooleanField(default=False, verbose_name="Offers"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                upload_to="static_cdn/admin/img", verbose_name="Photo"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="notifications",
            field=models.BooleanField(
                choices=[
                    ("0", "Everything"),
                    ("1", "Same as email"),
                    ("2", "No push notifications"),
                ],
                default="",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="zipcode",
            field=models.PositiveIntegerField(verbose_name="Zip/Postal code"),
        ),
    ]
