# Generated by Django 4.0.2 on 2022-02-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0002_remove_customuser_by_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.BooleanField(
                choices=[("0", "United states"), ("1", "Canada"), ("2", "France")]
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(upload_to="static_cdn/admin/img"),
        ),
    ]
