# Generated by Django 4.0.2 on 2022-02-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0004_remove_customuser_image_alter_customuser_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="image",
            field=models.ImageField(null=True, upload_to="static_cdn/admin/img"),
        ),
    ]
