# Generated by Django 4.0.2 on 2022-02-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0008_alter_customuser_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="notifications",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "Everything"),
                    ("1", "Same as email"),
                    ("2", "No push notifications"),
                ],
                default="",
                max_length=2,
                null=True,
            ),
        ),
    ]
