# Generated by Django 4.0.2 on 2022-02-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0009_alter_customuser_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
