# Generated by Django 4.0.2 on 2022-02-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0010_alter_customuser_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="notifications",
            field=models.CharField(
                choices=[
                    ("0", "Everything"),
                    ("1", "Same as email"),
                    ("2", "No push notifications"),
                ],
                default="options.0",
                max_length=1,
            ),
        ),
    ]
