# Generated by Django 4.0.2 on 2022-02-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0012_alter_customuser_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="notifications",
            field=models.CharField(
                choices=[
                    ("0", "Everything"),
                    ("1", "Same as email"),
                    ("2", "No push notifications"),
                ],
                default="",
                max_length=1,
            ),
        ),
    ]
