# Generated by Django 4.0.2 on 2022-02-25 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0013_alter_customuser_notifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="by_email_candidates",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="by_email_comments",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="by_email_offers",
        ),
        migrations.AddField(
            model_name="customuser",
            name="by_email",
            field=models.CharField(
                blank=True,
                choices=[("0", "Comments"), ("1", "Candidates"), ("2", "Offers")],
                default="",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="notifications",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "Everything"),
                    ("1", "Same as email"),
                    ("2", "No push notifications"),
                ],
                default="",
                max_length=1,
                null=True,
            ),
        ),
    ]
