# Generated by Django 4.0.2 on 2022-02-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0015_alter_customuser_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="by_email",
            field=models.CharField(
                blank=True,
                choices=[("0", "Comments"), ("1", "Candidates"), ("2", "Offers")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="notifications",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0", "Everything"),
                    ("1", "Same as email"),
                    ("2", "No push notifications"),
                ],
                max_length=1,
                null=True,
            ),
        ),
    ]
