# Generated by Django 4.0.2 on 2022-02-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0016_alter_customuser_by_email_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomUser",
            new_name="CustomUserModel",
        ),
    ]
