# Generated by Django 4.0.2 on 2022-03-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(verbose_name="Body"),
        ),
    ]
