# Generated by Django 4.0.2 on 2022-04-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("htmx", "0002_course_module"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["name", "last_updated"],
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.AlterModelOptions(
            name="module",
            options={
                "ordering": ["name", "last_updated"],
                "verbose_name_plural": "Modules",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="module",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Name"),
        ),
    ]
