# Generated by Django 4.0.2 on 2022-04-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("htmx", "0003_alter_course_options_alter_module_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={
                "ordering": ["last_updated", "title"],
                "verbose_name_plural": "Todos",
            },
        ),
        migrations.AddField(
            model_name="todo",
            name="created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Title"),
        ),
    ]
