# Generated by Django 4.0.2 on 2022-04-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("htmx", "0004_alter_todo_options_todo_created_todo_last_updated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todos",
                to="htmx.course",
            ),
        ),
        migrations.AddField(
            model_name="todo",
            name="module",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todos",
                to="htmx.module",
            ),
        ),
    ]
